name: Create metadata post

# Grant the action permission to write to the repository
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      post-title:
        description: The title of the post. This can be set as an action input or workflow input.
      start-end:
        description: The start date for the post. The format is `YYYY-MM-DD`. This can be set as an action input or workflow input.
      end-date:
        description: The end date for the post. The format is `YYYY-MM-DD`. This can be set as an action input or workflow input.

jobs:
  metadata-post:
    runs-on: ubuntu-latest
    name: Write metadata post
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write metadata post
        uses: ./
        with:
          github-username: katydecorah
          github-repository: archive
          source-bookmarks: recipes|_data/recipes.json
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "${{ env.title }}"
          git push
